### ISSUE TITLE
Handle emotes

### ISSUE THREAD

**Issue by malnormalulo** [DenisD3D/Minecraft2Discord#46]
The `/me <foo>` command in Minecraft produces an emote, e.g.,
Input: `/me waves`
Result: `* Malnormalulo waves`

Some folks like to use these conversationally, but M2D doesn't pick them up, leaving confusing gaps in the conversation. Would it be possible to pipe these to Discord?

**Comment by DenisD3D** [comment]
Okey so the me command work as the say command and directly send the chat message without triggering the event
Will try to fix that in the next update

**Comment by DenisD3D** [comment]
Should be handled in 2.0.5 update
