### ISSUE TITLE
Double messages in discord when webhooks for profile picture and name is turned to false

### ISSUE THREAD

**Issue by jinkhya** [DenisD3D/Minecraft2Discord#47]
Hello,

When changing
        # Enable the use of webhooks (customized profile picture and name)
        enabled = true
to false messages get sent twice in discord.
Version minecraft2discord-forge-1.16.4-2.0.5.jar

Oddly enough I'm using the 1.15 version of the mod and also disabled that setting and it's not duplicating chat.

**Comment by DenisD3D** [comment]
Yep i noticied this bug when making the new doc. I will fix that as soon as possible with some other minor issue i found.
Webhook mode should be working fine

**Comment by jinkhya** [comment]
awesome ty !

**Comment by DenisD3D** [comment]
Fix released on curseforge (M2D 2.0.6)
