### ISSUE TITLE
Players' messages are not sent to Discord when they are part of a /team with a prefix that has a space in it

### ISSUE THREAD

**Issue by Geforce132** [DenisD3D/Minecraft2Discord#49]
Hi!

We just started using the mod on our server and have not had any issues with it up until now. However, we just discovered that if a player is part of a team and that team has a prefix with a space in it (such as "[Server Helper]", "[Mod] ", etc.), the mod will log an error and not send any of their messages to Discord. If the player then leaves the team or joins another team that does not have a prefix with a space in it, their messages will start to be sent again.

[Here's the error](https://pastebin.com/VkXhwAGm) that is logged. We are using Minecraft 1.16.5, Forge 36.0.22 and 36.0.45, and Mc2Discord 2.0.6. Thanks!

**Comment by DenisD3D** [comment]
Hi, that's a know issue with the v2 of the mod !
I'm working on a v3 that is curently available in beta state on my discord : https://discord.gg/rzzd76c
You can use the beta version or wait for it's official release on curseforge
Denis

**Comment by DenisD3D** [comment]
Replacing the avatar_api from `avatar_api = "https://mc-heads.net/head/${player_name}/right"` to `avatar_api = "https://mc-heads.net/head/${player_uuid}/right"`should also fix the issue
