### ISSUE TITLE
incompatible modded server Red X After Updating to m2d 3.0.1 1.16.5

### ISSUE THREAD

**Issue by IchigoGames** [DenisD3D/Minecraft2Discord#51]
incompatible modded server Red X on server after updating minecraft2discord-forge-1.16.x-3.0.1 I had no Red X on server before updating a lot of the time this means a mod on the server getting flag as being required on Clintside as well of course this is not a serversider mod so show not be showing red x

Minecraft 1.16.5
Forge 35.1.35
minecraft2discord-forge-1.16.x-3.0.1

running minecraft2discord-forge-1.16.5-2.0.6 no red x Ignore EU server there on old version of pack.

![image](https://user-images.githubusercontent.com/11888162/111012416-8583b600-8361-11eb-97b5-8cf9399011cc.png)

After Updating to minecraft2discord-forge-1.16.x-3.0.1 

![image](https://user-images.githubusercontent.com/11888162/111012720-997be780-8362-11eb-94a2-5d1c25dcf396.png)

**Comment by IchigoGames** [comment]
oh much bigger issue and Probably needs its own report the mod is no longer working old or new version

**Comment by IchigoGames** [comment]
did config get reset at some point from minecraft2discord-forge-1.16.5-2.0.6  to minecraft2discord-forge-1.16.x-3.0.1 ?

**Comment by IchigoGames** [comment]
nvm it did get reset minecraft2discord-forge-1.16.5-2.0.6 should be fine then and ill stay on this version till issue with Red x is fixed.

**Comment by IchigoGames** [comment]
just to be clear the only change made from the first to the second was updating this mod on server.

**Comment by DenisD3D** [comment]
Hi @IchigoGames ,
Thanks for reporting the issue, i might have forget a line of code in the v3 that say that the mod is server side only... The issue must only be graphic. This should be fixed in 3.0.2
Thanks for reporting
Denis

PS : Please reopen this issue if the issue still isn't solved!
