### ISSUE TITLE
Server Crash Exception in server tick loop from minecraft2discord-forge-1.16.x-3.0.2

### ISSUE THREAD

**Issue by IchigoGames** [DenisD3D/Minecraft2Discord#52]
Server Crash Exception in server tick loop

i was just testing it on my desktop server before i added it to public server i was also trying to create a new config last time i updated it reset my old config so i wanted to make new one and add it at the same time but i  it started crashing.

Minecraft 1.16.5
Forge 36.0.55 and forge 36.0.58
mod version minecraft2discord-forge-1.16.x-3.0.2

Crash report https://pastebin.com/FK7sNfe6

logs https://www.dropbox.com/s/ps6xsu6iclxvoxu/latest.log?dl=0

**Comment by DenisD3D** [comment]
Fixed in 3.0.3 that is live on curseforge. Soory for the inconvenance
