### ISSUE TITLE
Custom usernames using Fakename mod have "§r" behind each name

### ISSUE THREAD

**Issue by Gitberham** [DenisD3D/Minecraft2Discord#53]
In the Discord channel, every user with a custom username (set with the [Fakename mod](https://www.curseforge.com/minecraft/mc-mods/fakename/files/3033139)) has a "§r" symbol behind their names. 

Not sure if this is something that could be fixed within MC2Discord. Sadly, the mod author does not currently have time to fix errors occuring in his mod.

**Comment by DenisD3D** [comment]
Will look into that. Thanks for reporting.

**Comment by DenisD3D** [comment]
Should be fixed in 3.0.7
If not please reopen this issue
Denis
