### ISSUE TITLE
Can't seem to use MC color codes in chat prefix configs

### ISSUE THREAD

**Issue by SargeRyong** [DenisD3D/Minecraft2Discord#54]
For example, setting minecraft_chat_format to a value that includes §1 does not color the chat prefix blue, but instead inserts an unknown character.  Using "\u00A71" to create the same effect results in no change to the message (possibly getting sanitized out?).

Sorry if there's a way to do this and I'm just not seeing it.

**Comment by DenisD3D** [comment]
Will investigate on this issue thanks for reporting

**Comment by DenisD3D** [comment]
Hi,
I tested with the following config :
![image](https://user-images.githubusercontent.com/35769613/123309192-e60bbd00-d524-11eb-886e-3935cca2dd0a.png)
and i ended with this result :
![image](https://user-images.githubusercontent.com/35769613/123309291-06d41280-d525-11eb-83e5-38f1cb9ae086.png)
Can you share more detail about your configuration (config, maybe OS, file encoding) ?
You may also want to join my discord : https://discord.gg/rzzd76c

**Comment by SargeRyong** [comment]
minecraft_chat_format = "<§1${member_nickname}§r> ${message}"

It's on a remote host - I believe it's CentOS.  Unsure about file encoding.

The above format results in this appearance:

https://i.imgur.com/rZuIHHN.png

**Comment by DenisD3D** [comment]
Solved replacing § by \u00a7
